// <auto-generated />
using System;
using ClinicaVeterinaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaVeterinaria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107104319_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.AnagraficaAnimale", b =>
                {
                    b.Property<Guid>("AnimaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ColoreMantello")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumeroMicrochip")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<bool>("PresenzaMicrochip")
                        .HasColumnType("bit");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AnimaleId");

                    b.HasIndex("CodiceFiscale");

                    b.ToTable("AnagraficheAnimali");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Armadietto", b =>
                {
                    b.Property<string>("NomeArmadietto")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomeArmadietto");

                    b.ToTable("Armadietti");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Cassetto", b =>
                {
                    b.Property<string>("NomeCassetto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArmadiettoNomeArmadietto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeArmadiettoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomeCassetto");

                    b.HasIndex("ArmadiettoNomeArmadietto");

                    b.ToTable("Cassetti");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Prodotto", b =>
                {
                    b.Property<string>("NomeProdotto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DittaFornitrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElencoUsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCassetto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NomeProdotto");

                    b.HasIndex("NomeCassetto");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Proprietario", b =>
                {
                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodiceFiscale");

                    b.ToTable("Proprietari");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Ricovero", b =>
                {
                    b.Property<Guid>("RicoveroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnagraficaAnimaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInizioRicovero")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneAnimale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHospitalized")
                        .HasColumnType("bit");

                    b.HasKey("RicoveroId");

                    b.HasIndex("AnagraficaAnimaleId");

                    b.ToTable("Ricoveri");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Vendita", b =>
                {
                    b.Property<Guid>("VenditaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("DataVendita")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeProdotto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("NumeroRicetta")
                        .HasColumnType("int");

                    b.HasKey("VenditaId");

                    b.HasIndex("CodiceFiscale");

                    b.HasIndex("NomeProdotto");

                    b.ToTable("Vendite");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Visita", b =>
                {
                    b.Property<Guid>("VisitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVisita")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneCura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsameObiettivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitaId");

                    b.HasIndex("AnimaleId");

                    b.ToTable("Visite");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.AnagraficaAnimale", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.Proprietario", "Proprietario")
                        .WithMany("AnagraficheAnimali")
                        .HasForeignKey("CodiceFiscale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Cassetto", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.Armadietto", "Armadietto")
                        .WithMany("Cassetti")
                        .HasForeignKey("ArmadiettoNomeArmadietto");

                    b.Navigation("Armadietto");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Prodotto", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.Cassetto", "Cassetto")
                        .WithMany()
                        .HasForeignKey("NomeCassetto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cassetto");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Ricovero", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.AnagraficaAnimale", "AnagraficaAnimale")
                        .WithMany()
                        .HasForeignKey("AnagraficaAnimaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnagraficaAnimale");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Vendita", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.Proprietario", "Proprietario")
                        .WithMany("Vendite")
                        .HasForeignKey("CodiceFiscale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaVeterinaria.Models.Entities.Prodotto", "Prodotto")
                        .WithMany("Vendite")
                        .HasForeignKey("NomeProdotto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Visita", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.AnagraficaAnimale", "AnagraficaAnimale")
                        .WithMany("Visite")
                        .HasForeignKey("AnimaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnagraficaAnimale");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaVeterinaria.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.AnagraficaAnimale", b =>
                {
                    b.Navigation("Visite");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Armadietto", b =>
                {
                    b.Navigation("Cassetti");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Prodotto", b =>
                {
                    b.Navigation("Vendite");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Entities.Proprietario", b =>
                {
                    b.Navigation("AnagraficheAnimali");

                    b.Navigation("Vendite");
                });
#pragma warning restore 612, 618
        }
    }
}
